Traceback (most recent call last):
  File "C:\Python\Python311\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Python\Python311\Lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\asyncio\base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "C:\Python\Python311\Lib\site-packages\nbclient\client.py", line 608, in async_setup_kernel
    yield
  File "C:\Python\Python311\Lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Python\Python311\Lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Python\Python311\Lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Not `inplace` argument
dep1_sort = dep1.sort_values( ['pop'] , ascending = False)

sort_values( ['year'] , ascending = True)
dep1_sort
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[46], line 4[0m
[0;32m      1[0m [38;5;66;03m# Not `inplace` argument[39;00m
[0;32m      2[0m dep1_sort [38;5;241m=[39m dep1[38;5;241m.[39msort_values( [[38;5;124m'[39m[38;5;124mpop[39m[38;5;124m'[39m] , ascending [38;5;241m=[39m [38;5;28;01mFalse[39;00m)
[1;32m----> 4[0m [43msort_values[49m( [[38;5;124m'[39m[38;5;124myear[39m[38;5;124m'[39m] , ascending [38;5;241m=[39m [38;5;28;01mTrue[39;00m)
[0;32m      5[0m dep1_sort

[1;31mNameError[0m: name 'sort_values' is not defined
NameError: name 'sort_values' is not defined

